baseURL = 'http://paulhenri.github.io/'
languageCode = 'fr-fr'
title = "Paul-H's cave"
theme = "photophobia"
SectionPageMenu="main"
[menu]
[[menu.main]]
  identifier = 'recipes'
  name = 'Recipes'
  title = 'recipes'
  url = '/recipes/index'
  weight = -110
[[menu.main]]
  identifier = 'links'
  name = 'Useful links'
  title = 'links'
  url = '/links/index'
  weight = -110
